# Generated by Django 5.0.6 on 2024-05-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='name',
        ),
    ]
